version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: dashboardkidslab
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - web
    labels:
      caddy: dashboardkidslab.hackerwerkstatt.de
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  web:
    external: true